services:
  - type: web
    name: TodoList
    dockerfilePath: Dockerfile
    plan: free
    branch: main
    region: singapore
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: "Production"
    runtime: docker
